name: Jacob Leon
markdown: redcarpet
highlighter: pygments
encoding: utf-8
github: https://www.github.com/jmleon1219
bitbucket: https://bitbucket.org/jacob_leon
about: Technology enthusiast & Chicago based consulting veteran
urls:
    - text: github
      url: https://github.com/jmleon1219
    - text: bitbucket
      url: https://bitbucket.org/jacob_leon
    - text: linkedin
      url: https://linkedin.com/in/JacobLeon
baseurl: 