name: Jacob Leon
markdown: redcarpet
highlighter: rouge
encoding: utf-8
github: https://www.github.com/exaem
about: Citizen of the world
urls:
    - text: github
      url: https://github.com/exaem
    - text: email
      url: mailto:exaem@exaem.co.uk
baseurl: 